hyderabad_locations = [
    "A C Guards",
    "A S Rao Nagar",
    "Adibatla",
    "Bhanur",
    "Abdullapur",
    "Abids",
    "Abids Circle",
    "Achyuthpuram",
    "Adarsh Nagar",
    "Addaguttala",
    "Addakan",
    "Addakul",
    "Adi Laxmi Narasimha Nagar",
    "Aero Nagar",
    "Afzalgunj",
    "Aghapura",
    "Ahmed Nagar",
    "Aliabagh",
    "Aliperi",
    "Alipura",
    "Alkapur",
    "Almas Guda",
    "Aloor",
    "Alwal",
    "Amangal",
    "Amberpet",
    "Amdapur",
    "Ameenpur",
    "Ameerpet",
    "AmriClassic",
    "Anajpur",
    "Anand Bagh",
    "Anand Nagar",
    "Andhra Bank Colony",
    "Anjapur",
    "Annajiguda",
    "Annajiguda Village",
    "Ansagar",
    "Anupurna Complex",
    "Anwal",
    "Aramghar",
    "Aremaishamma",
    "Aruna Colony",
    "Ashok Bazar",
    "Ashok Colony",
    "Ashok Nagar",
    "Ashram Road",
    "Ashwini Layout",
    "Asif Nagar",
    "Asif Nagar to Mehdipatnam",
    "Attapur Ring Road",
    "Aurangal",
    "Aushapur",
    "Ayappa Society",
    "Aziz Nagar",
    "B B Nagar",
    "B H E L Enclave",
    "B K Guda",
    "B N Reddy Nagar",
    "B T Road",
    "Baamrai",
    "Baba Nagar",
    "Babuji Nagar",
    "Bachupally",
    "Badangpet",
    "Badasingaram",
    "Badasingaram Village",
    "Badichowdi",
    "Badruka Enclave",
    "Bagh Amberpet",
    "Baghlingampally",
    "Bahadur Pally",
    "Bahadurpura",
    "Bairagiguda",
    "Bajpally",
    "Bakaram",
    "Balaji Hills",
    "Balaji Nagar",
    "Balanagar",
    "Balapur",
    "Balkmpet",
    "Ballaguda",
    "Bameerguda",
    "Bandalaguda Mandal",
    "Bandalguda",
    "Bandla Maisamma",
    "Bandlaguda",
    "BandlaGuda Jagir",
    "Bangalore Highway",
    "Banjara Green Colony",
    "Banjara Hills",
    "Bankstreet",
    "Banur",
    "Barani Colony",
    "Barkarpally",
    "Barkatpura",
    "Basheer Bagh",
    "Basvangudi",
    "Bazaarghat",
    "Beeramguda",
    "Begumpet",
    "Behrampada",
    "Beside Kamineni Hospital",
    "Beside Nehru Zodogical Park",
    "Between Airport & Hi-Tech City",
    "Bhagya Nagar",
    "Bhanu Enclave",
    "Bhanugudi",
    "Bharani Colony",
    "Bharat Nagar Colony",
    "Bharatguda",
    "Bhavish Enclave",
    "Bhawanipuram",
    "BHEL",
    "Bhoiguda",
    "Bholakpur",
    "Bhongir",
    "Bhoodan Pochampally",
    "Bibi Nagar",
    "Bijapur",
    "Bikaguda Park",
    "Binali",
    "Binjara Hills",
    "Blooming Meadows",
    "Boduppal",
    "Bogaram",
    "Boiguda",
    "Bolarum",
    "Bombay National",
    "Bonegiri",
    "Boothpur",
    "Boothpur Mandal",
    "Borabanda",
    "Borampet",
    "Bowenpally",
    "Bowrampet",
    "Brahim Patnam",
    "Brahmanwadi",
    "Brampet",
    "Buddha Nagar",
    "Capri Towers",
    "CBCID Colony",
    "Central Park",
    "Chaderghat",
    "Chaitanyapuri",
    "Chamapur",
    "Champapet",
    "Chanda Nagar",
    "Chandicherla",
    "Chandragiri",
    "Chandrayangutta",
    "Chappel Road",
    "Charkha Shirdi Sai Baba Colony",
    "Charlapally",
    "Charminar",
    "Charnaka",
    "Chaudpally",
    "Cheerala",
    "Chegunta",
    "Chevella",
    "Chikati Mamedi",
    "Chikkadapally",
    "Chikkoti Garden",
    "Chilkalguda",
    "Chilkur",
    "Chilkur Road",
    "Chintal",
    "Chintalkunta",
    "Chintradripet",
    "Chiragali Lane",
    "Chititra Medchal",
    "Choutuppal",
    "Close to Satyam Sai Temple",
    "Cyber City",
    "Cyber Enclave",
    "Cyber Hills",
    "Cyber Park",
    "Cyber Port",
    "Cyber Towers",
    "D D Colony",
    "Dairy Farm Road",
    "Dammaiguda",
    "Dayanand Nagar",
    "DeeptiShree Nagar",
    "Defence Colony",
    "Deshmukh Colony",
    "Devi Enclave",
    "Devi Kalyan Garden",
    "Dharam Karan Road",
    "Dholari Dhani",
    "Diamond Hills",
    "Diamond Point",
    "Digwal",
    "Dilshad Nagar",
    "Dilsukh Nagar",
    "Dilux Colony",
    "Dindigal",
    "Divya Sai Garden",
    "Doctor Colony",
    "Dodda Blapor",
    "Domalguda",
    "Dommaonda",
    "Donga Road",
    "Dubaka Medak District",
    "Dubbacharla",
    "Dubbacherla Village",
    "Dulapally",
    "Durga Bai Deshmukh Colony",
    "Durga Estate",
    "Durgam Sheru",
    "E Ashoka",
    "E C I L",
    "E C I L Cross Road",
    "East City",
    "Edula Nagula Pally",
    "Edulabad",
    "Ellampet",
    "Emerald Park",
    "Eros Garden",
    "Erragadda",
    "Erramanzil Colony",
    "Essamiya Bazar",
    "Essar Nagar",
    "Express Highway",
    "Fab City",
    "Farooq Nagar Mandal",
    "Fateh Nagar",
    "Father Balaiah Colony",
    "Feelkhana",
    "Financial district",
    "Flamingo",
    "Freen Lius Colony",
    "G D Matla Village",
    "G K Colony",
    "G P R Layout",
    "Gachibowli",
    "Gadwal",
    "Gagillapur",
    "Gaiewel",
    "Gajilaramavaram",
    "Galaxy",
    "Gandhi Nagar",
    "Gandimaismma",
    "Gandipet",
    "Gangaram",
    "Gatkeshwar",
    "Gattapally",
    "Gautam Nagar",
    "Gayatri Hills",
    "Gayatri Nagar",
    "General Bazar",
    "Getwel Pedchet Road",
    "Ghatkesar",
    "Ghatsingapore",
    "Gillaguda",
    "Gokul Plots",
    "Golconda Fort Area",
    "Golconda Mandal",
    "Golden Space",
    "Golkonda",
    "Gollur",
    "Gopanapally",
    "Gopanpally",
    "Gowana Tower",
    "Grampanchayati Layout",
    "Grand Meadows",
    "Grandular Residency",
    "Green Town",
    "Green Villa",
    "Greenhills Colony",
    "Greenlands",
    "Guendorampalli",
    "Gullagudran",
    "Gun Rock",
    "Gundramapally",
    "Gunrock",
    "Gunrock Enclave",
    "Gurukul",
    "Gyan Sagar",
    "H S Dagra",
    "H U D A",
    "Habsiguda",
    "Hafeezpet",
    "Haidarshakot",
    "Haminpur",
    "Hangi",
    "Hanumanth Nagar",
    "Hardware Park",
    "Hasan Nagar",
    "Hasmatpet",
    "Hayat Nagar",
    "Hema Nagar",
    "Highway Road",
    "Hilsort",
    "Himayat Nagar",
    "Himayatsagar",
    "Hi-Tech City",
    "Hosur",
    "Huda Layout",
    "Humayun Nagar",
    "Hyder nagar",
    "Hyderabad to Narsapur",
    "Hyderabad to Zaheerabad Highway",
    "Hyderbad to Bajipur Highway Chavella",
    "Hyder-B'lore Highway",
    "Hyderguda",
    "Hydersha Court",
    "Hypermarket",
    "I B Nagar",
    "I C R I S A T",
    "I T Park",
    "Ibrahim Patnam",
    "Ibrahimpet",
    "Ida Bollaram",
    "Ida Bontapally",
    "Inderbagh",
    "Indra Nagar",
    "Indra Park Road",
    "Intense Highway",
    "International Airport",
    "Ishwar Puri",
    "Ismia Bazar",
    "Isnapur",
    "J D Colony",
    "J N D U",
    "J N T U",
    "J P Dagra",
    "J P Durga Road",
    "Jadcherla",
    "Jahirabad",
    "Jalapalli",
    "Jallpally",
    "Jambagh",
    "Janagar",
    "Janapriya Utopia",
    "Jawahar Nagar",
    "Jayatgiri",
    "Jayprakash Nagar",
    "Jecherla",
    "Jeedimetla",
    "Jhangir Pet",
    "Jogipet",
    "Jubilee hills",
    "Jublee Hills",
    "K P R Colony",
    "Kachiguda",
    "Kadthal",
    "Kahjaramguda",
    "Kakaguda",
    "Kakatiya Nagar",
    "Kalwakurthy",
    "Kalyan Garden",
    "Kalyan nagar",
    "Kalyanguda",
    "Kalyani Gardens",
    "Kamala Nagar",
    "Kamalapuri Colony",
    "Kamareddy",
    "Kamdukur Mandal",
    "Kamman X Road",
    "Kanajiguda",
    "Kandhukargate",
    "Kandipur Mandal",
    "Kandlakoya",
    "Kandukur",
    "Kandukur Mandal",
    "Kangara Village",
    "Kapra",
    "Kardhal",
    "Kardhnoor",
    "Kareem Nagar Road",
    "Karkhana",
    "Karmanghat",
    "Karnaka",
    "Kartikeya Nagar",
    "Karwan",
    "Katangur",
    "Kattedan",
    "Kavadiguda",
    "Kaveri hills",
    "Kavuri Hills",
    "Kawadipally",
    "Kawakuty Mandal",
    "Kechiguda",
    "Keesara",
    "Keesaragutta",
    "Keshamoet",
    "Khader Bagh",
    "Khairatabad",
    "Khajaguda",
    "Kharnaka",
    "Khilwath",
    "Khudbulapur",
    "King Koti",
    "Kismathpur",
    "Kisnapur",
    "Kitnatpur",
    "Kodikonda",
    "Koheda",
    "Kohlapur",
    "Kokapet",
    "Kokapeta Village",
    "Kokutpally",
    "Kolarum",
    "Kollapadikala",
    "Kollur",
    "Kollur Village",
    "Kolluru",
    "Komareddy",
    "Kompally",
    "Kondakur",
    "Kondapur",
    "Kongara",
    "Kontapur",
    "Koramangala",
    "Korremula",
    "Kothaguda",
    "Kothapally",
    "Kothapet",
    "Kothur",
    "Koti",
    "Kotta Guda",
    "Kowarpalli",
    "Kowkoor Village",
    "Koyda",
    "KPHB Colony",
    "Krishna Nagar",
    "Kucharam",
    "Kukatpally",
    "Kundan Bagh",
    "Kundanpally",
    "Kundli",
    "Kuntloor",
    "Kurma Guda",
    "Kurnool",
    "Kusaiguda",
    "L B Main Road",
    "L B Nagar",
    "L I C Colony",
    "Lahiri Garden Park",
    "Lakdi-ka-pul",
    "Lake View",
    "Lakudaram",
    "Lalitha Nagar",
    "Laluma Garden",
    "Lamoor",
    "Lanco Hills",
    "Langer House",
    "Laxmi Mega Central City",
    "Laxmiguda",
    "Legend",
    "Limoore",
    "Lingampally",
    "Lingoigauda",
    "Lives Park",
    "Lothkunta",
    "Lower Tank Bund",
    "M C A Colony",
    "M E S Colony",
    "M G Road",
    "M I G Colony",
    "M L A's Colony",
    "M M T S Railway Station",
    "M R Palle",
    "Machbolaram",
    "Madepally",
    "Madhapur",
    "Madhava Hills",
    "Madhura Nagar",
    "Madhwa Nagar",
    "Madinaguda",
    "Madura",
    "Maharaj Gunj",
    "Maheshwar Mandal",
    "Maheshwaram",
    "Maheshwaram",
    "Mahindra Hills",
    "Mainkonda",
    "Majidpur",
    "Makid",
    "Malakpet",
    "Malaysian Township",
    "Malguda",
    "Malikaarjuna Colony",
    "Malkajgiri",
    "Malkapur",
    "Malkapuram",
    "Malkaram",
    "Malkaram Village",
    "Mallaguda",
    "Mallampet",
    "Mallapur",
    "Mallepalli",
    "Mallpur",
    "Mamadipalli",
    "Managuda",
    "Manasanapalli",
    "Manchirevulu",
    "Mandal",
    "Mandimelaram",
    "Mangalapalli",
    "Manik Nagar",
    "Manikonda",
    "Maninagar",
    "Mankal Village",
    "Mankhal",
    "Manoharabad",
    "Manokonda",
    "Mansanpally",
    "Mansoorabad",
    "Marredpally",
    "Maruthi nagar",
    "Masab Tank",
    "Masinaguda",
    "Medak",
    "Medak Road",
    "Medchal",
    "Medchal & Kalkal Village",
    "Medipally",
    "Meerkhanpet",
    "Meerpet",
    "Mehdipatnam",
    "Mehdipatnam Ring Road",
    "Melpa",
    "Mettuguda",
    "Midhani",
    "Midjil",
    "Minerva Complex",
    "Miryalaguda",
    "Miyapur",
    "Moazzamjahi Market",
    "Modi Nagar",
    "Mohan Nagar",
    "Moinabad",
    "Mokilla",
    "Molkur Road",
    "Mominpet",
    "Moosapet",
    "Moti Nagar",
    "Moulali",
    "Mount Opera",
    "Mount Road",
    "Mucherla",
    "Mudimuyal",
    "Mujapur",
    "Muktaguda",
    "Muktandi",
    "Mulugu Mandal",
    "Mumbai Highway",
    "Munaganoor",
    "Muneedabad",
    "Murad Nagar",
    "Musheerabad",
    "Mustabad",
    "Muttangi",
    "Naarayanguda",
    "Nacharam",
    "Nadergul",
    "Nafarani Village",
    "Nagaipally",
    "Nagaram",
    "Nagaram Village",
    "Nagarguda",
    "Nagarjuna",
    "Nagarjuna Sagar Road",
    "Nagole",
    "Nagpur Highway",
    "Nakkapally",
    "Nalgonda",
    "Nallagandla",
    "Nallakunta",
    "Nampally",
    "Nampally Raiway Station",
    "Nanak Nagar",
    "Nanakramguda",
    "Nandagiri Hills",
    "Nandigama",
    "Nandigram",
    "Nandipally",
    "Nankaramguda",
    "Naragam",
    "Narapally",
    "Narapelli",
    "Narayan Kher",
    "Narayanguda",
    "Narayanmet",
    "Nareelpally",
    "Narguda Vilage",
    "Narkedpally",
    "Narsapur",
    "Narsingi",
    "Naryanguda",
    "Nasaram",
    "National Highway",
    "Navodaya Nagar",
    "Nazimpet",
    "Near Bollaram Railway Station",
    "Near Chandana Brother",
    "Near Chitrapuri Colony",
    "Near Infosys",
    "Near Loyala Accademy",
    "Near Nanopark",
    "Near Paradise Hotel",
    "Near Pragathi Resort",
    "Near S B H",
    "Near Sangeet Theater",
    "Near St. Ann's",
    "Near Word & Deed School",
    "Nehru Nagar",
    "Neknampur",
    "Neredmet",
    "Netaji Nagar",
    "New Bowenpally",
    "NH-5",
    "NH-7",
    "NH-9",
    "Nighpul Highway",
    "Nizampet",
    "Nr. Hotel Viceroy",
    "Officers Colony",
    "Old Alwal",
    "Old Safli Guda",
    "Om Vihar Colony",
    "Opp Hotel Siddarth",
    "Opp. Airport Road",
    "Opp. Shalimar Theatre",
    "Orangal Highway",
    "Osman Ganj",
    "Osmani Avenue",
    "Osmaniya University",
    "Others/Hyderabad",
    "Others/Secunderabad",
    "Outer Ring Road",
    "P G Road",
    "P J R Layout",
    "P R Nagar",
    "P S Rao Nagar",
    "Padampuri",
    "Padma Colony",
    "Padma Rao Nagar",
    "Padmanabham Nagar",
    "Padmanayar",
    "Padmavati Nagar",
    "Palkampally",
    "Panchayat",
    "Panjagutta",
    "Paolavaram",
    "Papireddy nagar",
    "Paraballa",
    "Paradise Circle",
    "Pargi",
    "Parklane",
    "Parveda",
    "Pashamailaram",
    "Pasmamla",
    "Pasmurlul",
    "Patancheru Mandal",
    "Pedakakani",
    "Peddakamalalamia",
    "Peddamberpet",
    "Peddashapur",
    "Peelambarpet",
    "Peeramcheru",
    "Pet Bashirabad",
    "Petlla Burj",
    "Picket",
    "Pochampally",
    "Poddattur Village",
    "Pothgal",
    "Pragati Nagar",
    "Pragati Resorts",
    "Prakash Nagar",
    "Prashanth Nagar",
    "Pratap Reddy Nagar",
    "Prayathi Nagar",
    "Pulimamidi",
    "Puppalguda",
    "Pusapet",
    "Puttaparthy",
    "Qutbullapur",
    "R C Puram",
    "R K Puram",
    "R P Road",
    "R R District",
    "R R Nagar",
    "R R Towers",
    "R T C Cross Road",
    "Rachloor",
    "Raghvendra Nagar",
    "Raidurg",
    "Raisal",
    "Rajbhavan",
    "Rajendra Nagar",
    "Rajhmundry",
    "Rajiv Gandhi International Airport",
    "Rajiv Gandhi Nanotech Park",
    "Rajiv Nagar",
    "Rajiv Rahadari Road",
    "Raju Nagar",
    "Ram Chandra Puram",
    "Ram Nagar",
    "Ramakrishnapuram",
    "Ramanathapur",
    "Ramayanpet",
    "Ramdas Colony",
    "Ramdas Nagar",
    "Ramkote",
    "Ramoji Film City",
    "Rampally",
    "Rancheda Kalol Road",
    "Ranga Reddy",
    "Raniganj",
    "Ranipet",
    "Rantabad",
    "Rasela Bazar",
    "Rasoolpura",
    "Ravikol",
    "Red Hills",
    "Reti Bowli",
    "Ring Road",
    "Rock Garden",
    "Rocktown Colony",
    "Rudraram",
    "S B I Colony",
    "S D Road",
    "S M R Square",
    "S P Road",
    "S R Nagar",
    "Sadashivpet",
    "Safiguda",
    "Sagar Highway",
    "Sagar Juna Highway",
    "Sagar Ring Road",
    "Sahabguda",
    "Sahara States",
    "Saheb Nagar",
    "Sai Anurag Janachaytanya Laout",
    "Sai Nagar",
    "Sai Sudhir Deg",
    "Saibaba Nagar",
    "Saidabad",
    "Saidapur",
    "Saifabad",
    "Sainathpuram",
    "Sainikpuri",
    "Saket",
    "Saket Township",
    "Salarjung Colony",
    "Saleem Nagar Colony",
    "Sanath Nagar",
    "Sancharpuri",
    "Sanghi Temple",
    "Sangi Nagar",
    "Sanjay Nagar",
    "Sanjeeva Reddy Nagar",
    "Santosh Nagar",
    "Saraswati Nagar",
    "Saraswatiguda",
    "Sarojoni Devi Road",
    "Saroor Nagar",
    "Satamrai",
    "Sathanwri",
    "Satyanagar",
    "Secretariat",
    "Secretariat Colony",
    "Secundarabad",
    "Secunderabad Club",
    "Secunderabad Railway Station",
    "Seethaphal Mandi",
    "Seetharambagh",
    "Serlingampally",
    "Shad Nagar",
    "Shahdab",
    "Shahdab Road",
    "Shahibaug",
    "Shaikpet",
    "Shakti Nagar",
    "Shameerpet",
    "Shamshabad",
    "Shamshabad to Maheshwaram",
    "Shanakar Nidhi R P Road",
    "Shankar Hills",
    "Shankarpally",
    "Shanti Nagar",
    "Shapur",
    "Sharada Nagar",
    "Sherpally",
    "Shivam Road",
    "Shivaram Palli",
    "Shivareddy Pally",
    "Shivrampally",
    "Shyam Karan Road",
    "Siddharth Nagar",
    "Siddipet",
    "Sikh Village",
    "Silicon Ridge",
    "Sindhi Colony",
    "Singapore City",
    "Singareni",
    "Sitaphalmandi",
    "Sivarampalli",
    "Snehita Hills",
    "Software Park",
    "Somajiguda",
    "Spring Field",
    "Sri Sailam Highway",
    "Sri vani Enclave",
    "Srinagar Colony",
    "Srinivas Colony",
    "Srinivas Nagar",
    "Srirampally",
    "Srisailam",
    "Srisailam Highway",
    "Srisailam Road",
    "Station Road",
    "Subhash Nagar",
    "Suchitra",
    "Sultan Bazaar",
    "Sultanpur",
    "Sunamkothuru",
    "Suraram",
    "Surya Enclave",
    "Surya Nagar",
    "Tadbund-Centre Point",
    "Takkaguda",
    "Tandhur",
    "Tankbund Road",
    "Taramethipet",
    "Tarnaka",
    "Teachers Colony",
    "Telephone Colony",
    "Tellapur",
    "Tellpur Osmannagar",
    "Thukkuguda",
    "Thumkunta",
    "Thummaluru",
    "Tilak Nagar",
    "Tilak Road",
    "Timmaipally",
    "Timmapur",
    "Timmipally",
    "Tirumala Hills",
    "Tirumala Nagar",
    "Tolata",
    "Tolichowki",
    "Tolkata",
    "Tondangi",
    "Tondapally",
    "Toopran",
    "Toopranpet",
    "Torruru",
    "Trimulgherry",
    "Tropbazaar",
    "Tspa junction",
    "Tukaram Gateway",
    "Tukkuguda",
    "Tukkuguda",
    "Tulsinagar",
    "Tumaloor",
    "Tumkunta",
    "Tummaluru",
    "Tupran",
    "Turapally",
    "Turka yamjal",
    "Turkapally",
    "Turkayanmjal",
    "Turrur",
    "Tusaram Colony",
    "Tutaguda",
    "Twin City",
    "Uddachellapur",
    "Udyog Nagar",
    "Uppal",
    "Uppal Mandal",
    "Uppalguda",
    "Upparpally",
    "Ushamullapudi",
    "Usman Nagar",
    "V S T Nagar",
    "Vadargal",
    "Vanasthali Puram",
    "Vangallerao Nagar",
    "Vasanth Nagar",
    "Vasavi Colony",
    "Vasavi Nagar",
    "Vattinagulapally",
    "Vayu Puri",
    "Vayu Vihar",
    "Vengalarao Nagar",
    "Venkatadri Enclave",
    "Venkatapuram",
    "Venkateshwar Colony",
    "Venkatgiri",
    "Venkatraopet",
    "Vennela Township",
    "Vidya Nagar",
    "Vidyut Nagar",
    "Vijayawada Highway",
    "Vijaynagar Colony",
    "Vijaywada",
    "Vijya Nagar",
    "Vikarabad",
    "Vikashpuri",
    "Vikrampuri",
    "Vivekanand Nagar",
    "Vrindavan Colony",
    "Warangal Highway",
    "West Maredpally",
    "Whitefield",
    "Yadagirigutta",
    "Yadamma Nagar",
    "Yakutpura",
    "Yamjal",
    "Yapral",
    "Yellareddyguda",
    "Yenkapally",
    "Yousufguda",
    "Zaheerabad",
]
